name: CI

on:
  push:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Validar sintaxe Python
    - working-directory: python
    - run: python3 -m compileall .
    - name: Testes python
      working-directory: python
      run: python3 test_app.py 
    - name: Testar ambiente
      run: echo "Github Actions funcionando" 
    - name: Build Docker
      working-directory: python
      run: docker build -t github-laboratorio-python .

    - name: Run Docker
      run: docker run --rm github-laboratorio-python
        

      
